const $=s=>document.querySelector(s);let current=null,record=null;
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data}
function notice(err){$('#message').textContent=err?.message||String(err)}
async function load(){try{const d=await api('disruptions');$('#cards').innerHTML=d.disruptions.map(x=>{const ship=d.shipments.find(s=>s.id===x.shipment_id);return `<article class="card"><div class="card-top"><strong>${safe(x.id)}</strong><span class="severity ${safe(x.severity)}">${safe(x.severity)}</span></div><h3>${safe(ship.sku)} · ${safe(ship.destination_id.replace('FAC-',''))}</h3><p>${safe(x.summary)}</p><div class="card-meta"><span>SHIPMENT ${safe(ship.id)}</span><span>${safe(ship.units)} UNITS</span></div><button class="button" data-id="${safe(x.id)}">Investigate →</button></article>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>investigate(b.dataset.id));await audit()}catch(e){notice(e)}}
async function investigate(id){$('#message').textContent='';current=null;record=null;$('#workspace').innerHTML='<div class="empty-state">Reading linked objects and checking alternatives…</div>';location.hash='investigation';try{current=await api('investigate',{disruption_id:id});render(id)}catch(e){$('#workspace').innerHTML=`<div class="empty-state"><span>◇</span><h3>No feasible response found</h3><p>${safe(e.message)}</p></div>`}}
function render(id){const p=current.proposal,g=current.gate;const evidence=p.evidence.map(x=>`<tr><td>${safe(x.object_type)}</td><td>${safe(x.object_id)}</td><td>${safe(x.field)}</td><td>${safe(x.value)}</td></tr>`).join('');const checks=Object.entries(g.checks).map(([k,v])=>`<div class="check"><span class="${v?'pass':'fail'}">${v?'✓':'✕'}</span> ${safe(k.replaceAll('_',' '))}</div>`).join('');$('#workspace').innerHTML=`<div class="workspace-grid"><div class="panel"><div class="eyebrow">CASE ${safe(id)} / RECOMMENDATION</div><h3 style="margin-top:8px">Alternate inventory response</h3><div class="result ${g.allowed_for_review?'':'blocked'}"><div><strong>${g.allowed_for_review?'Ready for human review':'Blocked by policy'}</strong><small>${safe(p.rationale)}</small></div></div><div class="stat-row"><div class="stat"><small>TIME RECOVERED</small><strong>${safe(p.days_saved)} days</strong></div><div class="stat"><small>INCREMENTAL COST</small><strong>$${safe(p.incremental_cost_usd.toLocaleString())}</strong></div><div class="stat"><small>ARRIVAL DAY</small><strong>${safe(p.estimated_arrival_day)}</strong></div></div><p>Reserve <b>${safe(p.quantity)} units</b> from <b>${safe(p.inventory_id)}</b> and dispatch via <b>${safe(p.route_id)}</b>.</p><h3>Policy checks</h3><div class="checks">${checks}</div><div class="actions" id="actions"></div></div><div class="panel"><h3>Read tool trace</h3><div class="flow">${current.trace.map(t=>`<span>${safe(t.tool)}</span>`).join('')}</div><h3 style="margin-top:25px">Grounding evidence</h3><table class="table"><thead><tr><th>OBJECT</th><th>ID</th><th>FIELD</th><th>VALUE</th></tr></thead><tbody>${evidence}</tbody></table></div></div>`;renderActions()}
function renderActions(){const a=$('#actions');if(!a)return;if(!current.gate.allowed_for_review){a.innerHTML='<span class="hint">This recommendation cannot be submitted under the current policy.</span>';return}if(!record){a.innerHTML='<button class="button" id="submit">Submit for approval →</button><span class="hint">No inventory changes before approval.</span>';$('#submit').onclick=async()=>{try{record=await api('proposals',current);renderActions();audit()}catch(e){notice(e)}};return}if(record.status==='pending'){a.innerHTML='<input id="approver" placeholder="Approver name" aria-label="Approver name"><button class="button" id="approve">Approve</button><button class="button danger" id="reject">Reject</button>';for(const [id,approve] of [['approve',true],['reject',false]])$('#'+id).onclick=async()=>{try{record=await api(`proposals/${record.id}/decision`,{approver:$('#approver').value,approve});renderActions();audit()}catch(e){notice(e)}};return}if(record.status==='approved'){a.innerHTML=`<span class="hint">Approved by ${safe(record.approver)}</span><button class="button" id="execute">Execute local simulation →</button>`;$('#execute').onclick=async()=>{try{record=await api(`proposals/${record.id}/execute`,{});renderActions();audit()}catch(e){notice(e)}};return}a.innerHTML=`<span class="hint">${safe(record.status.toUpperCase())} · ${safe(record.approver)}</span>`}
async function audit(){try{const d=await api('audit');$('#integrity').textContent=d.chain_valid?'VALID':'FAILED';$('#audit-list').innerHTML=d.events.length?d.events.slice().reverse().map(x=>`<div class="audit-item"><b>#${x.seq}</b><span>${safe(x.event.replaceAll('_',' '))}</span><time>${safe(new Date(x.at*1000).toLocaleString())}</time></div>`).join(''):'<span class="hint">No decisions recorded yet.</span>'}catch(e){notice(e)}}
$('#refresh-audit').onclick=audit;load();

